# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x07netauto\"\x88\x01\n\tBGPUpdate\x12\x0e\n\x06router\x18\x01 \x01(\t\x12\x10\n\x08neighbor\x18\x02 \x01(\t\x12\x12\n\nremote_asn\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0e\n\x06uptime\x18\x05 \x01(\t\x12\x13\n\x0bprefixes_rx\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"2\n\x0b\x42GPSnapshot\x12#\n\x07updates\x18\x01 \x03(\x0b\x32\x12.netauto.BGPUpdate\"3\n\x0f\x41\x63knowledgement\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x8c\x01\n\x10TelemetryService\x12@\n\x0eStreamBGPState\x12\x12.netauto.BGPUpdate\x1a\x18.netauto.Acknowledgement(\x01\x12\x36\n\x0eGetLatestState\x12\x0e.netauto.Empty\x1a\x14.netauto.BGPSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BGPUPDATE']._serialized_start=29
  _globals['_BGPUPDATE']._serialized_end=165
  _globals['_BGPSNAPSHOT']._serialized_start=167
  _globals['_BGPSNAPSHOT']._serialized_end=217
  _globals['_ACKNOWLEDGEMENT']._serialized_start=219
  _globals['_ACKNOWLEDGEMENT']._serialized_end=270
  _globals['_EMPTY']._serialized_start=272
  _globals['_EMPTY']._serialized_end=279
  _globals['_TELEMETRYSERVICE']._serialized_start=282
  _globals['_TELEMETRYSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
